Repository Steemhunt/dixel-v2-contract, pull requests merged in 2022-06, with the labels that each got.

#4 Optimization
  README.md
  contracts/DixelClubV2Factory.sol
  contracts/DixelClubV2NFT.sol
  contracts/IDixelClubV2NFT.sol
  contracts/SVGGenerator.sol
  contracts/Shared.sol
  contracts/lib/ERC721Initializable.sol
  contracts/lib/StringUtils.sol
  test/DixelClubV2Factory.test.js
  test/DixelClubV2NFT.test.js
Labels: enhancement

#17 Pixels array: pack 2 pixels into each uint8
  contracts/Constants.sol
  contracts/DixelClubV2Factory.sol
  contracts/DixelClubV2NFT.sol
  contracts/IDixelClubV2Factory.sol
  contracts/SVGGenerator.sol
  package-lock.json
  test/DixelClubV2NFT.test.js
  test/fixtures/test-input.json
  test/fixtures/test-svg-complex.svg
Labels: enhancement

#22 all: typo - remove blank.
  contracts/DixelClubV2NFT.sol
  contracts/SVGGenerator.sol
  contracts/lib/StringUtils.sol
Labels: minor

#26 contracts: early check that the fee is correct.
  contracts/DixelClubV2Factory.sol
Labels: enhancement, minor

#27 cleanup & added missing test cases
  test/DixelClubV2Factory.test.js
  test/DixelClubV2NFT.test.js
Labels: enhancement
